# Generated by Django 4.1.7 on 2023-03-30 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20221120_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='tag',
            field=models.CharField(choices=[('tag1', 'Tag 1'), ('tag2', 'Tag 2'), ('tag3', 'Tag 3'), ('tag4', 'Tag 4'), ('tag5', 'Tag 5')], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 58, 21, 635602)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 58, 21, 635602)),
        ),
    ]
