# Generated by Django 4.1.7 on 2023-03-30 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0037_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='programming_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 11, 35, 30, 860205)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 11, 35, 30, 860205)),
        ),
    ]
