# Generated by Django 4.1.7 on 2023-03-31 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_question_db_programming_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='tag',
            field=models.CharField(default='python', max_length=300),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 10, 6, 2, 275412)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 10, 6, 2, 275412)),
        ),
    ]
