# Generated by Django 4.1.7 on 2023-03-31 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0040_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 18, 16, 22, 245613)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 18, 16, 22, 245613)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='max_marks',
            field=models.IntegerField(default=1),
        ),
    ]
