# Generated by Django 4.1.7 on 2023-04-01 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_alter_exam_model_end_time_alter_exam_model_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomquestion',
            name='choice',
            field=models.CharField(default='E', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 6, 40, 54, 463548)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 6, 40, 54, 463548)),
        ),
    ]
