# Generated by Django 3.2 on 2022-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mob',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='roll_no',
            field=models.IntegerField(max_length=200),
        ),
    ]
