# Generated by Django 3.2 on 2022-11-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20221108_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mob',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='roll_no',
            field=models.CharField(max_length=200),
        ),
    ]
