# Generated by Django 3.2 on 2022-11-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
