# Generated by Django 3.2 on 2022-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='gallery')),
                ('des', models.CharField(max_length=500)),
            ],
        ),
    ]
