# Generated by Django 4.1.7 on 2023-03-31 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_alter_exam_model_end_time_alter_exam_model_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuexam_db',
            name='random_questions',
            field=models.ManyToManyField(related_name='random_questions_set', to='questions.question_db'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='qpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question_paper'),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sturesults_db',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
