# Generated by Django 4.1.7 on 2023-04-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_stuexam_db_random_questions_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.IntegerField(default=0)),
                ('web', models.IntegerField(default=0)),
                ('ml', models.IntegerField(default=0)),
                ('dsa', models.IntegerField(default=0)),
                ('dbms', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
